# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preference.ui',
# licensing of 'preference.ui' applies.
#
# Created: Mon Nov 19 11:03:19 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import images

class Ui_Preference(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(387, 299)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        Dialog.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_image = QtWidgets.QLabel(Dialog)
        self.lb_image.setMinimumSize(QtCore.QSize(0, 50))
        self.lb_image.setObjectName("lb_image")
        self.verticalLayout_2.addWidget(self.lb_image)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cb_datetime = QtWidgets.QComboBox(self.frame)
        self.cb_datetime.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cb_datetime.setObjectName("cb_datetime")
        self.gridLayout.addWidget(self.cb_datetime, 2, 1, 1, 1)
        self.le_seperator = QtWidgets.QLineEdit(self.frame)
        self.le_seperator.setObjectName("le_seperator")
        self.gridLayout.addWidget(self.le_seperator, 3, 1, 1, 1)
        self.le_decimal = QtWidgets.QLineEdit(self.frame)
        self.le_decimal.setObjectName("le_decimal")
        self.gridLayout.addWidget(self.le_decimal, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_file = QtWidgets.QLineEdit(self.frame)
        self.le_file.setObjectName("le_file")
        self.horizontalLayout.addWidget(self.le_file)
        self.tb_open = QtWidgets.QToolButton(self.frame)
        self.tb_open.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/images/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_open.setIcon(icon)
        self.tb_open.setObjectName("tb_open")
        self.horizontalLayout.addWidget(self.tb_open)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.cb_locale = QtWidgets.QComboBox(self.frame)
        self.cb_locale.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cb_locale.setObjectName("cb_locale")
        self.gridLayout.addWidget(self.cb_locale, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pb_ok = QtWidgets.QPushButton(self.frame)
        self.pb_ok.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/images/Success.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ok.setIcon(icon1)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_2.addWidget(self.pb_ok)
        self.pb_cancel = QtWidgets.QPushButton(self.frame)
        self.pb_cancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/images/Cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_cancel.setIcon(icon2)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.le_file, self.tb_open)
        Dialog.setTabOrder(self.tb_open, self.cb_locale)
        Dialog.setTabOrder(self.cb_locale, self.cb_datetime)
        Dialog.setTabOrder(self.cb_datetime, self.le_seperator)
        Dialog.setTabOrder(self.le_seperator, self.le_decimal)
        Dialog.setTabOrder(self.le_decimal, self.pb_ok)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Preference", None, -1))
        self.lb_image.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Date/Time Format:", None, -1))
        self.tb_open.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Decimal", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "File:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Seperator:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Locale", None, -1))
        self.pb_ok.setText(QtWidgets.QApplication.translate("Dialog", "OK", None, -1))
        self.pb_cancel.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

